### ISSUE TITLE
Godot 3 supported?

### ISSUE THREAD

**Issue by brylie** [RodZill4/godot-openstreetmap#1]
Does this project work with Godot 3?

**Comment by MrMinimal** [comment]
@brylie The project files (.cfg) seem to be for Godot 2.0, I don't know if there is a porting effort going on.

I just downloaded 2.1 and started the project, still works like a charm, OSM download might take a while. Check the console output.

**Comment by RodZill4** [comment]
Yes I started porting the project to 3.0. There are still a few problems (mainly ground textures) and I wanted to reimplement the roofs algorithm using GDNative.

**Comment by kamikaze** [comment]
any help needed? I can do Python )

**Comment by RodZill4** [comment]
Godot 3.0 is now supported !

**Comment by MrMinimal** [comment]
Amazing, will try it out the second I am home. Thank you so much for the effort!

**Comment by brylie** [comment]
You rock!
